<a href="https://colab.research.google.com/github/Dikshanya/SIH/blob/master/CropPrediction/Crop_prediction_RandomForest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
# from google.colab import files
# uploaded = files.upload()
# import io
data = pd.read_csv('./cpdata.csv')

print(data.head(1))
lbl=data['label']


   temperature   humidity        ph    rainfall label
0    20.879744  82.002744  6.502985  202.935536  rice


In [ ]:
label= pd.get_dummies(data.label).iloc[: , 1:]
data= pd.concat([data,label],axis=1)
data.drop('label', axis=1,inplace=True)
print('The data present in one row of the dataset is')
print(data.tail(10))

The data present in one row of the dataset is
      temperature   humidity        ph  ...  rice  watermelon  wheat
3090    24.693689  85.569676  6.353107  ...     0           1      0
3091    24.543570  84.608083  6.211749  ...     0           1      0
3092    25.897623  81.966648  6.277245  ...     0           1      0
3093    26.633312  84.317568  6.560444  ...     0           1      0
3094    25.357947  80.458463  6.903020  ...     0           1      0
3095    25.287846  89.636679  6.765095  ...     0           1      0
3096    26.638386  84.695469  6.189214  ...     0           1      0
3097    25.331045  84.305338  6.904242  ...     0           1      0
3098    26.897502  83.892415  6.463271  ...     0           1      0
3099    26.986037  89.413849  6.260839  ...     0           1      0

[10 rows x 34 columns]


In [ ]:
X = data.iloc[:, 0:4].values
y = data.iloc[: ,4:].values
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
from sklearn.ensemble import RandomForestClassifier

regressor = RandomForestClassifier(n_estimators=5, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(accuracy_score(y_test, y_pred))

0.9096774193548387


In [ ]:

import numpy as np
l=[]
l1=[]
l1.append(float (21.587))
l1.append(float (82.788))
l1.append( float (6.249))
l1.append(float (276.655))
l.append(l1)
l2=[] 
l2.append(float (27.536))
l2.append(float (89.929))
l2.append(float (6.619))
l2.append(float (	45.485))
l.append(l2)
l3=[]
l3.append(float (24.485))
l3.append(float (83.206))
l3.append(float (6.1325))
l3.append(float (192.231))
l.append(l3)

predictcrop=np.array(l)
from sklearn import preprocessing
scalar = preprocessing.MinMaxScaler()
crops=['rice','wheat','mungbean','Tea','millet','maize','lentil','jute','cofee','cotton',
       'ground nut','peas','rubber','sugarcane','tobacco','kidney beans','moth beans','coconut','blackgram','adzuki beans',
       'pigeon peas','chick peas','banana','grapes','apple','mango','muskmelon','orange','papaya','pomegranate','watermelon']
cr='rice'
from sklearn.datasets import make_blobs
predictcrop = scalar.fit_transform(predictcrop)
predictions = regressor.predict(predictcrop)
print(predictions)
for k in range(0,len(predictions)):
  max_pred=np.amax(predictions[k])
  max_indx = np.where(predictions[k] == max_pred)
  threshold=0.8*max_pred
  c=[]
  for i in range(0,30):
      if(predictions[k][i]>threshold):
          c.append(crops[i])
      i=i+1
  print(c)

[[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
['Tea']
['muskmelon']
['maize']
