In [1]:
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
import matplotlib.pylab as plt

In [2]:
df = pd.read_csv("pH Dataset - Sheet1.csv")

In [3]:
df.head()

R    G    B    pH
0  133   98   30  7.05
1  172  139  106  6.80
2  176  152  114  6.63
3  158  132   51  6.64
4  197  164  123  8.35

In [4]:
sat_hue_df = pd.DataFrame(columns=['Saturation', 'Mean_hue_sat'])
for i in range(0,len(df)):
  red=df['R'][i]
  green=df['G'][i]
  blue=df['B'][i]
  maximum=max([red,blue,green])
  minimum=min([red,blue,green])
  value=maximum
  cost=maximum-minimum
  if value==0:
    saturation=0
  else:
    saturation=float(cost)/float(value)
  if cost==0:
    hue=0
  elif maximum==red:
    x=float(green-blue)/float(cost)
    hue=60*(x%6)
  elif maximum==green:
    x=float(blue-red)/float(cost)
    hue = 60 * (x+ 2);
  elif maximum==blue:
    x=float(red-green)/float(cost)
    hue = 60 * (x+4);
  print(i,saturation,saturation+hue)
  sat_hue_df = sat_hue_df.append({'Saturation': saturation, 'Mean_hue_sat': saturation+hue}, ignore_index=True)
print(sat_hue_df)

0 0.7744360902255639 40.38608657566246
1 0.38372093023255816 30.38372093023256
2 0.3522727272727273 37.12646627565982
3 0.6772151898734177 46.097775937536966
4 0.3756345177664975 33.61887776100974
5 0.4789473684210526 32.1272990167727
6 0.24083769633507854 22.414750739813336
7 0.09580838323353294 352.59580838323353
8 0.5526315789473685 38.409774436090224
9 0.6756756756756757 42.67567567567568
10 0.5864661654135338 37.50954308849046
11 0.5397727272727273 35.9081937799043
12 0.43349753694581283 27.706224809673085
13 0.4319526627218935 33.30866499148901
14 0.41714285714285715 26.718512720156554
15 0.4567901234567901 32.889222555889226
16 0.5555555555555556 39.88888888888889
17 0.5476190476190477 34.46066252587992
18 0.5769230769230769 35.910256410256416
19 0.4294478527607362 33.00087642418931
20 0.3956043956043956 30.395604395604394
21 0.4685714285714286 33.395400696864115
22 0.24154589371980675 35.04154589371981
23 0.4946236559139785 33.10331930808789
24 0.23788546255506607 40.2378854625

In [5]:
# Labels are the values we want to predict
labels = np.array(df['pH'])# Remove the labels from the features
# axis 1 refers to the columns
features= df.drop('pH', axis = 1)# Saving feature names for later use
# features = sat_hue_df
feature_list = list(features.columns)# Convert to numpy array
features = np.array(features)
print(features)

[[133  98  30]
 [172 139 106]
 [176 152 114]
 [158 132  51]
 [197 164 123]
 [190 147  99]
 [191 162 145]
 [167 151 153]
 [152 121  68]
 [148 118  48]
 [133 103  55]
 [176 137  81]
 [203 155 115]
 [169 136  96]
 [175 134 102]
 [162 128  88]
 [162 131  72]
 [168 128  76]
 [156 119  66]
 [163 131  93]
 [182 146 110]
 [175 138  93]
 [207 186 157]
 [186 144  94]
 [227 209 173]
 [187 155 117]
 [226 186 125]
 [196 146 109]
 [203 168 140]
 [155 137  89]
 [157 134  80]
 [179 129  67]
 [230 181 123]
 [208 161 119]
 [196 150 101]
 [176 139  69]
 [182 136  50]
 [128 105  27]
 [185 155  91]
 [152 122  52]
 [229 210 152]
 [255 220 162]
 [176 169 123]
 [173 128  43]
 [169 145  85]
 [189 164 110]
 [167 154  99]
 [186 154  97]
 [164 160 113]
 [158 150 111]]


In [6]:
# Using Skicit-learn to split data into training and testing sets
from sklearn.model_selection import train_test_split# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [7]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (37, 3)
Training Labels Shape: (37,)
Testing Features Shape: (13, 3)
Testing Labels Shape: (13,)


In [8]:
train_features

array([[152, 121,  68],
       [158, 132,  51],
       [191, 162, 145],
       [255, 220, 162],
       [167, 154,  99],
       [186, 154,  97],
       [162, 128,  88],
       [148, 118,  48],
       [162, 131,  72],
       [227, 209, 173],
       [196, 150, 101],
       [179, 129,  67],
       [133,  98,  30],
       [169, 145,  85],
       [196, 146, 109],
       [208, 161, 119],
       [190, 147,  99],
       [155, 137,  89],
       [176, 137,  81],
       [182, 136,  50],
       [172, 139, 106],
       [175, 138,  93],
       [176, 152, 114],
       [173, 128,  43],
       [176, 139,  69],
       [186, 144,  94],
       [229, 210, 152],
       [133, 103,  55],
       [207, 186, 157],
       [156, 119,  66],
       [158, 150, 111],
       [182, 146, 110],
       [167, 151, 153],
       [176, 169, 123],
       [175, 134, 102],
       [203, 168, 140],
       [185, 155,  91]])

In [9]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)# Train the model on training data
rf.fit(train_features, train_labels);

In [10]:
# Use the forest's predict method on the train data
predictions = rf.predict(train_features)# Calculate the absolute errors
errors = abs(predictions - train_labels)# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / train_labels)# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Mean Absolute Error: 0.18 degrees.
Accuracy: 97.33 %.


In [11]:
# Use the forest's predict method on the test data
predictions = rf.predict(test_features)# Calculate the absolute errors
errors = abs(predictions - test_labels)# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.69 degrees.


In [12]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / test_labels)# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 90.86 %.


In [13]:
input = [[172, 139, 106]]
output = rf.predict(input)
print(output)

[6.97509]


In [14]:
#In order to quantify the usefulness of all the variables in the entire random forest,
#we can look at the relative importances of the variables.
#The importances returned in Skicit-learn represent how much including a particular variable 
#improves the prediction.

In [15]:
# Get numerical feature importances
importances = list(rf.feature_importances_)# List of tuples with variable and importance
feature_importances = [(feature, round(importance, 2)) for feature, importance in zip(feature_list, importances)]# Sort the feature importances by most important first
feature_importances = sorted(feature_importances, key = lambda x: x[1], reverse = True)# Print out the feature and importances 
[print('Variable: {:20} Importance: {}'.format(*pair)) for pair in feature_importances];

Variable: B                    Importance: 0.48
Variable: R                    Importance: 0.26
Variable: G                    Importance: 0.26


# SVM

In [16]:
from sklearn.model_selection import train_test_split# Split the data into training and testing sets
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25)

In [17]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (37, 3)
Training Labels Shape: (37,)
Testing Features Shape: (13, 3)
Testing Labels Shape: (13,)


In [18]:
from sklearn.svm import SVC
from sklearn.svm import SVR
from sklearn.svm import LinearSVC

# svclassifier = LinearSVC()
svclassifier = SVR()
svclassifier.fit(train_features, train_labels)

/home/harla/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
  tol=0.001, verbose=False)

In [19]:
# Use the forest's predict method on the train data
predictions = svclassifier.predict(train_features)# Calculate the absolute errors
errors = abs(predictions - train_labels)# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / train_labels)# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Mean Absolute Error: 0.14 degrees.
Accuracy: 97.89 %.


In [20]:
predictions = svclassifier.predict(test_features)# Calculate the absolute errors
errors = abs(predictions - test_labels)# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.32 degrees.


In [21]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / test_labels)# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 95.36 %.


In [22]:
input = [[197, 164, 123]]
output = svclassifier.predict(input)
print(output)
output = rf.predict(input)
print(output)

[8.08155835]
[6.95227]


In [23]:
input = [[176, 152, 114]]
output = svclassifier.predict(input)
print(output)
output = rf.predict(input)
print(output)

[6.73030835]
[6.81125]


In [24]:
import pickle
pickle.dump(svclassifier, open('model.pkl','wb'))
# Loading model to compare the results
model = pickle.load(open('model.pkl','rb'))
print(model.predict([[158, 132, 51]]))

[6.73969153]
